package com.gafinance.db;

// Generated Jul 15, 2013 1:05:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Contribution generated by hbm2java
 */
public class Contribution implements java.io.Serializable {

	private Integer id;
	private String userId;
	private Integer amount;
	private String method;
	private Date createdate;
	private Date updatedate;
	private Byte deletedind;

	public Contribution() {
	}

	public Contribution(String userId, Integer amount, String method,
			Date createdate, Date updatedate, Byte deletedind) {
		this.userId = userId;
		this.amount = amount;
		this.method = method;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.deletedind = deletedind;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public Byte getDeletedind() {
		return this.deletedind;
	}

	public void setDeletedind(Byte deletedind) {
		this.deletedind = deletedind;
	}

}
