package com.gafinance.db;

// Generated Jul 15, 2013 1:05:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String name;
	private String description;
	private String website;
	private String videoUrl;
	private String image1;
	private String image2;
	private String image3;
	private Integer targetAmount;
	private Integer raisedAmount;
	private Integer approved;
	private Date currentdate;
	private Date updatedate;
	private Integer deletedind;

	public Project() {
	}

	public Project(Integer userId, String name, String description,
			String website, String videoUrl, String image1, String image2,
			String image3, Integer targetAmount, Integer raisedAmount,
			Integer approved, Date currentdate, Date updatedate, Integer deletedind) {
		this.userId = userId;
		this.name = name;
		this.description = description;
		this.website = website;
		this.videoUrl = videoUrl;
		this.image1 = image1;
		this.image2 = image2;
		this.image3 = image3;
		this.targetAmount = targetAmount;
		this.raisedAmount = raisedAmount;
		this.approved = approved;
		this.currentdate = currentdate;
		this.updatedate = updatedate;
		this.deletedind = deletedind;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getVideoUrl() {
		return this.videoUrl;
	}

	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	public String getImage1() {
		return this.image1;
	}

	public void setImage1(String image1) {
		this.image1 = image1;
	}

	public String getImage2() {
		return this.image2;
	}

	public void setImage2(String image2) {
		this.image2 = image2;
	}

	public String getImage3() {
		return this.image3;
	}

	public void setImage3(String image3) {
		this.image3 = image3;
	}

	public Integer getTargetAmount() {
		return this.targetAmount;
	}

	public void setTargetAmount(Integer targetAmount) {
		this.targetAmount = targetAmount;
	}

	public Integer getRaisedAmount() {
		return this.raisedAmount;
	}

	public void setRaisedAmount(Integer raisedAmount) {
		this.raisedAmount = raisedAmount;
	}

	public Integer getApproved() {
		return this.approved;
	}

	public void setApproved(Integer approved) {
		this.approved = approved;
	}

	public Date getCurrentdate() {
		return this.currentdate;
	}

	public void setCurrentdate(Date currentdate) {
		this.currentdate = currentdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public Integer getDeletedind() {
		return this.deletedind;
	}

	public void setDeletedind(Integer deletedind) {
		this.deletedind = deletedind;
	}

}
