package com.gafinance.db;

// Generated Jul 15, 2013 1:05:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String type;
	private String role;
	private Date createdate;
	private Date updatedate;
	private Byte deletedind;

	public Role() {
	}

	public Role(String type, String role, Date createdate, Date updatedate,
			Byte deletedind) {
		this.type = type;
		this.role = role;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.deletedind = deletedind;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public Byte getDeletedind() {
		return this.deletedind;
	}

	public void setDeletedind(Byte deletedind) {
		this.deletedind = deletedind;
	}

}
