package com.gafinance.db;

// Generated Jul 15, 2013 1:05:23 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Integer roleId;
	private String firstName;
	private String mi;
	private String lastName;
	private String email;
	private String password;
	private Date createdate;
	private Date updatedate;
	private Boolean deletedind;

	public User() {
	}

	public User(Integer roleId, String firstName, String mi, String lastName,
			String email, String password, Date createdate, Date updatedate,
			Boolean deletedind) {
		this.roleId = roleId;
		this.firstName = firstName;
		this.mi = mi;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.deletedind = deletedind;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMi() {
		return this.mi;
	}

	public void setMi(String mi) {
		this.mi = mi;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public Boolean getDeletedind() {
		return this.deletedind;
	}

	public void setDeletedind(Boolean deletedind) {
		this.deletedind = deletedind;
	}

}
